server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kingcall?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false
    username: root
    password: www1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/kingcall?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false
      username: root
      password: www1234
      driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/kingcall?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false
      username: root
      password: www1234
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 30
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      stat-view-servlet:
        login-username: kingcall
        login-password: www1234
